require_relative "../test_setup"
require_relative "map"

describe Map do
  def do_action(input)
    described_class.new(input).tap(&:find_antinode_coordinates).serialize
  end

  it "runs the given example" do
    input = <<~INPUT.strip
      ............
      ........0...
      .....0......
      .......0....
      ....0.......
      ......A.....
      ............
      ............
      ........A...
      .........A..
      ............
      ............
    INPUT

    output = <<~OUTPUT.strip
      ......#....#
      ...#....0...
      ....#0....#.
      ..#....0....
      ....0....#..
      .#....A.....
      ...#........
      #......#....
      ........A...
      .........A..
      ..........#.
      ..........#.
    OUTPUT

    expect(do_action(input)).to eq output
  end

  maps = [
    <<~MAP,
      ....
      .A..
      ..A.
      ....

      #...
      .A..
      ..A.
      ...#
    MAP
    <<~MAP,
      .....
      AA...
      ..A..
      .....

      #....
      AA#..
      ..A..
      ...##
    MAP
  ].each_with_index do |map, i|
    # next unless i == 1

    input, output = map.split("\n\n").map { |block| block.split("\n").map(&:strip).join("\n") }
    it "works on #{input}" do
      expect(do_action(input)).to eq output
    end
  end
end
